# Partition & ASM-Label Shared disks

  - name: ASM-storage | partition devices
    shell: parted {{ item.1.device }} "mklabel gpt mkpart primary 1 -1"
    args:
       creates: "{{ item.1.device}}{{partition_suffix}}"
    with_subelements:
        - "{{asm_diskgroups}}"
        - disk
    run_once: "{{ configure_cluster}}"
    when: partition_devices and asm_diskgroups is defined
    tags: asmstorage,partition

  - include: dm-multipath-kpartx.yml
    when: multipath == 'dm-multipath' and partition_devices and asm_diskgroups is defined

  - include: "{{ device_persistence }}.yml"
