---

   device_persistence: asmlib
   oracle_asm_init_dg: data

   asm_diskgroups:        # ASM Diskgroups used for DB-storage. Should map to dict asm_storage_layout. 
    - diskgroup: data
      properties:
        - {redundancy: external, ausize: 4}
      attributes:
        - {name: compatible.rdbms, value: 11.2.0.4.0}
        - {name: compatible.asm, value: "{{ oracle_install_version_gi }}"}
      disk:
        - {device: /dev/sdc, asmlabel: data01}
    - diskgroup: fra
      properties:
        - {redundancy: external, ausize: 4}
      attributes:
        - {name: compatible.rdbms, value: 11.2.0.4.0}
        - {name: compatible.asm, value: "{{ oracle_install_version_gi }}"}
      disk:
        - {device: /dev/sdd, asmlabel: fra01}
