---


- name: Host configuration
  hosts: vbox-si-fs
  user: vagrant
  become: yes
  roles:
     - common
     - orahost

- name: Database Server Installation & Database Creation
  hosts: vbox-si-fs
  user: vagrant
  become: yes
  roles:
     - oraswdb-install
     - oradb-manage-db

- name: Install cx_oracle
  hosts: vbox-si-fs
  user: vagrant
  become: yes
  roles:
     - cxoracle

- name: Configure Logrotate
  hosts: vbox-si-fs
  user: vagrant
  become: yes
  roles:
     - orahost-logrotate

- name: Customize database(s)
  hosts: vbox-si-fs
  user: vagrant
  become: yes
  roles:
     - oradb-manage-pdb
     - oradb-manage-tablespace
     - oradb-manage-parameters
     - oradb-manage-roles
     - oradb-manage-users
     - oradb-manage-grants
     - oradb-manage-services
