- name: Manage redologs
  oracle_redo:
        hostname={{ ansible_hostname }}
        service_name={{ item.oracle_db_name }}
        user={{ db_user }}
        password={{ db_password_cdb }}
        mode={{ db_mode }}
        size={{ item.redolog_size }}
        groups={{ item.redolog_groups }}
  environment: "{{oracle_env}}"
  run_once: "{{ configure_cluster}}"
  with_items:
      - "{{oracle_databases}}"
  when: oracle_databases is defined and item.redolog_size is defined and item.redolog_groups is defined
  become_user: "{{ oracle_user }}"
  register: param_change
  tags: initparams
