---

   autostartup_service: True
   oracle_dbf_dir_fs: /u02/oradata
   oracle_reco_dir_fs: /u03/fra

   rman_script_dir:                  /u01/app/oracle/rman
   rman_log_dir:                     /u01/app/oracle/rman/log
   rman_retention_policy:            "RECOVERY WINDOW OF 14 DAYS"
   rman_channel_disk:                "FORMAT   '/u10/rmanbackup/%d/%d_%T_%U'"
   rman_controlfile_autobackup_disk: "'/u10/rmanbackup/%d/%d_%F'"

   oracle_pdbs:
     - pdb_name: orclpdb1
#       datafile_dest: /u02/oradata/DB122U
       cdb: db122
       home: dbhome1
       oracle_version_db: 12.2.0.1
       listener_port: 1522
       state: present
       init_parameters:
         - {name: db_create_file_dest, value: '/u02/oradata', scope: both, state: present}

       tablespaces:
         - { name: users, size: 10M, bigfile: True, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }
       roles:
         - name: approle1
           grants:
              - create session
              - create table
              - select any table
              - select any dictionary
           state: present

       users:
          - schema: appluser
            state: present
            grants:
               - connect


   oracle_databases:                                           # Dictionary describing the databases to be installed
        - home: dbhome1                                        # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/12.1.0.2/racdb)
          oracle_version_db: 12.2.0.1                          # Oracle versiono
          oracle_home: /u01/app/oracle/product/12.2.0.1/dbhome1
          oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
          oracle_db_name: db122                                # Database name
          oracle_db_instance_name: db122i
          oracle_db_unique_name: db122u
          oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
          is_container: "true"                                # (true/false) Is the database a container database
          storage_type: FS                                     # Database storage to be used. ASM or FS. 
          oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
          oracle_db_mem_totalmb: 1000
          redolog_size: 20M
          redolog_groups: 3
          state: present
          listener_name: LSNR1522
          listener_port: 1522
          oracle_init_params: "local_listener='localhost:1522'"
          init_parameters:
            - {name: audit_trail, value: 'NONE', scope: spfile, state: present}
            - {name: control_management_pack_access, value: 'NONE', scope: spfile, state: present}

          users:
             - schema: c##check_mk
               state: present
               grants:
                  - connect
                  - select_catalog_role

          rman_jobs:
             - name: parameter
               immediate: True                                # write rman configuration to database dureing playbook execution
             - name: offline_level0
               disabled: False
               day: "*"
               weekday: "0"
               hour: "05"
               minute: "30"

        - home: dbhome2
          oracle_version_db: 12.1.0.2                          # Oracle versiono
          oracle_edition: EE                                   # The edition of database-server (EE,SE,SEONE)
          oracle_db_name: db121                                # Database name
          oracle_db_unique_name: db121u
          oracle_db_type: SI                                   # Type of database (RAC,RACONENODE,SI)
          is_container: "false"                                # (true/false) Is the database a container database
          storage_type: FS                                     # Database storage to be used. ASM or FS. 
          oracle_database_type: MULTIPURPOSE                   # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
          oracle_db_mem_totalmb: 1500
          redolog_size: 20M
          redolog_groups: 3
          state: present
          listener_name: LSNR1523
          listener_port: 1523
          oracle_init_params: "local_listener='localhost:1523'"

          tablespaces:
            - { name: tools, size: 10M, bigfile: True, autoextend: false , next: 5M, maxsize: 500M, content: permanent, state: present }

          users:
             - schema: check_mk
               state: present
               grants:
                  - connect
                  - select_catalog_role
          roles:
            - name: approle1
              grants:
                - create session
                - create table
                - select any table
                - select any dictionary
              state: present


          rman_jobs:
             - name: parameter
               immediate: True                                # write rman configuration to database dureing playbook execution
             - name: offline_level0
               disabled: False
               day: "*"
               weekday: "0"
               hour: "05"
               minute: "30"
