---

  - name: Extract files to ORACLE_HOME (gi)
    unarchive: src={{ oracle_stage }}/{{ item.filename }}  dest={{ oracle_home_gi }} copy=no
    with_items: "{{oracle_sw_image_gi}}"
    args:
        creates: "{{ oracle_home_gi }}/root.sh"
    become: yes
    become_user: "{{ grid_install_user }}"
    tags:
      - oragridswunpack
    when: checkgiinstall.stdout != "1" and oracle_install_version_gi == item.version and oracle_sw_copy and oracle_sw_unpack

  - name: Extract files to ORACLE_HOME (gi) (from remote location)
    unarchive: src={{ oracle_stage_remote }}/{{ item.filename }}  dest={{ oracle_home_gi }} copy=no
    with_items: "{{oracle_sw_image_gi}}"
    args:
        creates: "{{ oracle_home_gi }}/root.sh"
    become: yes
    become_user: "{{ grid_install_user }}"
    tags:
    - oragridswunpack
    when: checkgiinstall.stdout != "1" and oracle_install_version_gi == item.version

  # Check for an existing GRID_HOME before reinstallation of OPatch
  - name: Check for file GridSetup.sh
    no_log: true
    stat: path={{ oracle_home_gi }}/gridSetup.sh
    register: stat_gridsetup_result
    run_once: "{{ configure_cluster}}"
    #when: master_node

  - name: State of GridSetup.sh
    assert:
      that: "stat_gridsetup_result.stat.exists == True"
      msg: "Cannot find {{ oracle_home_gi }}/gridSetup.sh }}"
    run_once: "{{ configure_cluster}}"
    #when: master_node
  # unarchive didn't worked in some environments. => using unzip directly
  # Overwrite existing files from OPatch due to Note 2321749.1
  - name: Distribute latest opatch
    shell: unzip -o -d {{oracle_home_gi}} {{opatcharchive}}
    become: yes
    become_user: "{{ grid_install_user }}"
    when: oracle_sw_image_gi_psu is defined and checkgiinstall.stdout != "1"

  - name: Install cvuqdisk rpm
    yum: name="{{ oracle_home_gi }}/cv/rpm/{{ cvuqdisk_rpm }}" state=present
    when: configure_cluster
    tags: cvuqdisk
    ignore_errors: true

  - name: Recreate ORACLE_HOME (gi) on other nodes
    file: name={{ oracle_home_gi }} state=absent
    when: configure_cluster and inventory_hostname != cluster_master and checkgiinstall.stdout != "1"

  - name: Recreate ORACLE_HOME (gi) on other nodes
    file: name={{ oracle_home_gi }}  mode=775 owner={{ oracle_user }} group={{ oracle_group }} state=directory
    when: configure_cluster and inventory_hostname != cluster_master and checkgiinstall.stdout != "1"

  - name: Setup response file for install (GI)
    template: src=grid-install.rsp.{{ oracle_install_version_gi }}.j2 dest={{ oracle_rsp_stage }}/{{ oracle_grid_responsefile }} owner="{{ grid_install_user }}" group={{ oracle_group }} mode=600 backup=yes
    with_items: "{{asm_diskgroups}}"
    run_once: "{{ configure_cluster}}"
    tags:
      - responsefilegi
    when: checkgiinstall.stdout != "1" and item.diskgroup == oracle_asm_init_dg

  # returncode of gridSetup.sh is always <> 0 => forced exit 0
  - name: Apply Release Update on ORACLE_HOME
    shell: "{{oracle_home_gi}}/gridSetup.sh -silent -applyPSU {{ oracle_stage_remote }}/{{ oracle_install_version_gi }}/{{item.patchid}} -waitforcompletion ; exit 0"
    become: yes
    become_user: "{{ grid_install_user }}"
    with_items:
      - "{{ oracle_sw_image_gi_psu }}"
    register: command_result
    failed_when: "'Successfully applied the patch.' not in command_result.stdout_lines"
    when: oracle_sw_image_gi_psu is defined and oracle_install_version_gi == item.version and checkgiinstall.stdout != "1"

  - debug: msg="Ignore the failure [FATAL] [INS-40426] in output from gridSetup.sh -applyPSU"
    when: command_result is defined and oracle_sw_image_gi_psu is defined

  - debug: msg={{item.stdout_lines}}
    with_items:
      - "{{command_result.results}}"
    when: oracle_sw_image_gi_psu is defined and checkgiinstall.stdout != "1"

  - name: Install Grid Infrastructure
    shell: "{{ oracle_home_gi }}/gridSetup.sh -responseFile {{ oracle_rsp_stage }}/{{ oracle_grid_responsefile }} -waitforcompletion -ignorePrereq -silent"
    become: yes
    become_user: "{{ grid_install_user }}"
    run_once: "{{ configure_cluster}}"
    tags:
      - oragridinstall
    when: checkgiinstall.stdout != "1" #and oracle_sw_unpack
    register: giinstall

  - debug: var=giinstall.stdout_lines
    run_once: "{{ configure_cluster}}"
    when: checkgiinstall.stdout != "1"

  - name: Run oraInstroot script after installation
    shell: "{{ oracle_inventory_loc }}/orainstRoot.sh"
    become: yes
    tags:
      - runroot
    when: checkgiinstall.stdout != "1"

  - name: Run root script after installation (Master Node)
    shell: "{{ oracle_home_gi }}/root.sh"
    become: yes
    run_once: "{{ configure_cluster}}"
    tags:
      - runroot
    when: checkgiinstall.stdout != "1"
    register: rootmaster

  - debug: var=rootmaster.stdout_lines
    run_once: "{{ configure_cluster}}"
    when: checkgiinstall.stdout != "1"

  - name: Run root script after installation (Other Nodes)
    shell: "sleep {{ item.0 * 60 }}; {{ oracle_home_gi }}/root.sh"
    become: yes
    with_indexed_items: "{{groups[hostgroup]}}"
    tags:
      - runroot
    #when: not master_node and checkgiinstall.stdout != "1" and inventory_hostname == item.1
    when: configure_cluster and inventory_hostname != cluster_master and inventory_hostname == item.1 and checkgiinstall.stdout != "1"
    register: rootother

  - debug: var=rootother.stdout_lines
    #when: not master_node and checkgiinstall.stdout != "1"
    when: configure_cluster and inventory_hostname != cluster_master and checkgiinstall.stdout != "1"
    ignore_errors: True

  - name: Execute ConfigTools
    shell: "{{ oracle_home_gi }}/gridSetup.sh -executeConfigTools -responseFile {{ oracle_rsp_stage }}/{{ oracle_grid_responsefile }} -silent"
    become: yes
    become_user: "{{ grid_install_user }}"
    run_once: "{{ configure_cluster}}"
    tags:
      - runconfigtool
    when: run_configtoolallcommand and checkgiinstall.stdout != "1"
    ignore_errors: true
    register: configtool
