---
   configure_host_disks: true

   host_fs_layout:
    - vgname: orabasevg
      state: present
      filesystem:
        - {mntp: /u01, lvname: orabaselv, lvsize: 20G, fstype: ext4}
      disk:
        - {device: /dev/sdb, pvname: /dev/sdb1}

    - vgname: oradatavg
      state: present
      filesystem:
        - {mntp: /u02, lvname: oradatalv, lvsize: 15G, fstype: ext4}
        - {mntp: /u03, lvname: orafralv, lvsize: 12G, fstype: ext4}
      disk:
        - {device: /dev/sdc, pvname: /dev/sdc1}
